---
- name: My playbook copy
  hosts: all
  become: true
  tasks:
    - name: copy a file
      copy:
        src: /home/ansadmin/index.html
        dest: /var/www/html
        mode: 0666
        owner: bharu
...
