---
- name: my test playbook
  hosts: webservers
  become: true
  tasks:
    - name: stopping httpd
      service:
        name: httpd
        state: stopped
      when: ansible_os_family == "RedHat"

    - name: uninstalling httpd
      yum:
        name: httpd
        state: removed
      when: ansible_os_family == "RedHat"

    - name: stopping httpd
      apt:
        name: httpd
        state: stopped
      when: ansible_os_family == "Debian"

    - name: uninstalling httpd
      apt:
        name: uninstalling httpd
        state: removed
      when: ansible_os_family == "Debian"
...
